### ISSUE TITLE
Fix build: FPS overlay missing t_app field

### ISSUE THREAD

**Issue by danieljs-dev** [danieljs-dev/cub3D#53]
File: src/render/fps.c

After merging the FPS overlay feature into the development branch, the project fails to build because the struct s_app does not contain the field ft_ms_display, which is used by the FPS overlay to display milliseconds per frame (MS/frame).

This causes a compilation error when fps.c tries to access the missing field.

How to reproduce:

Clone the [Merge pull request](https://github.com/danieljs-dev/cub3D/commit/cdf2645a71bdf7c0ecc360d2fb31095e1110dead) https://github.com/danieljs-dev/cub3D/pull/52 [from danieljs-dev/feat/fps-counter](https://github.com/danieljs-dev/cub3D/commit/cdf2645a71bdf7c0ecc360d2fb31095e1110dead)

Run make.

The compilation fails in fps.c because struct s_app does not define ft_ms_display.

The overlay code expects this field to store and display the MS/frame value.

Suggestion: add the ft_ms_display field to t_app in include/structs.h, ensuring the change follows Norminette rules and does not affect behavior outside the FPS/MS overlay.
